version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        networks:
            - rs-network

#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '44001:8025'

#  rabbitmq:
#    image: rabbitmq:latest
#    hostname: rs_rabbitmq
#    env_file:
#      - rmq/rmq_variables.env
#    ports:
#      - "15673:15672"
#      - "5673:5672"
#    volumes:
#      - ./rmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
#    networks:
#      - rs-network

    redis:
        image: 'redis:alpine'
        ports:
            - "6380:6379"
        networks:
            - rs-network

    postgres:
        image: 'postgres:13.1-alpine'
        working_dir: /var/www/app
        volumes:
            - '..:/var/www/app'
        environment:
            - POSTGRES_USER=rs-db
            - POSTGRES_PASSWORD=rs-pass
            - POSTGRES_DB=rs
        ports:
            - '44004:5432'
        networks:
            - rs-network

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/app
        volumes:
            - '..:/var/www/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '44000:80'
        networks:
            - rs-network

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www/app
        volumes:
            - '..:/var/www/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - rs-network

networks:
    rs-network: